Pim\Bundle\CatalogBundle\Model\Family:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
        - Pim\Bundle\CatalogBundle\Validator\Constraints\Immutable:
            properties:
                - code
    properties:
        code:
            - NotBlank: ~
            - Regex:
                pattern: /^[a-zA-Z0-9_]+$/
                message: Family code may contain only letters, numbers and underscores
            - Length:
                max: 100
        translations:
            - Valid: ~

Pim\Bundle\CatalogBundle\Model\FamilyTranslation:
    properties:
        label:
            - Length:
                max: 100
