parameters:
    pim_versioning.repository.version.class: Pim\Bundle\VersioningBundle\Doctrine\ORM\VersionRepository

services:
    pim_versioning.repository.version:
        class: %pim_versioning.repository.version.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_versioning.entity.version.class%]
        tags:
            - { name: 'pim_repository' }
