parameters:
    pim_catalog.entity.product.class:                     Pim\Bundle\CatalogBundle\Model\Product
    pim_catalog.entity.product_value.class:               Pim\Bundle\CatalogBundle\Model\ProductValue
    pim_catalog.entity.association.class:                 Pim\Bundle\CatalogBundle\Model\Association
    pim_catalog.entity.completeness.class:                Pim\Bundle\CatalogBundle\Model\Completeness
    pim_catalog.entity.association_type.class:            Pim\Bundle\CatalogBundle\Model\AssociationType
    pim_catalog.entity.category.class:                    Pim\Bundle\CatalogBundle\Model\Category
    pim_catalog.entity.category_translation.class:        Pim\Bundle\CatalogBundle\Model\CategoryTranslation
    pim_catalog.entity.group.class:                       Pim\Bundle\CatalogBundle\Model\Group
    pim_catalog.entity.group_type.class:                  Pim\Bundle\CatalogBundle\Model\GroupType
    pim_catalog.entity.attribute.class:                   Pim\Bundle\CatalogBundle\Model\Attribute
    pim_catalog.entity.attribute_translation.class:       Pim\Bundle\CatalogBundle\Model\AttributeTranslation
    pim_catalog.entity.attribute_group.class:             Pim\Bundle\CatalogBundle\Model\AttributeGroup
    pim_catalog.entity.attribute_group_translation.class: Pim\Bundle\CatalogBundle\Model\AttributeGroupTranslation
    pim_catalog.entity.attribute_option.class:            Pim\Bundle\CatalogBundle\Model\AttributeOption
    pim_catalog.entity.attribute_option_value.class:      Pim\Bundle\CatalogBundle\Model\AttributeOptionValue
    pim_catalog.entity.attribute_requirement.class:       Pim\Bundle\CatalogBundle\Model\AttributeRequirement
    pim_catalog.entity.family.class:                      Pim\Bundle\CatalogBundle\Model\Family
    pim_catalog.entity.family_translation.class:          Pim\Bundle\CatalogBundle\Model\FamilyTranslation
    pim_catalog.entity.channel.class:                     Pim\Bundle\CatalogBundle\Model\Channel
    pim_catalog.entity.currency.class:                    Pim\Bundle\CatalogBundle\Model\Currency
    pim_catalog.entity.locale.class:                      Pim\Bundle\CatalogBundle\Model\Locale
    pim_catalog.entity.metric.class:                      Pim\Bundle\CatalogBundle\Model\Metric
    pim_catalog.entity.product_media.class:               Pim\Bundle\CatalogBundle\Model\ProductMedia
    pim_catalog.entity.product_price.class:               Pim\Bundle\CatalogBundle\Model\ProductPrice
    pim_catalog.entity.product_template.class:            Pim\Bundle\CatalogBundle\Model\ProductTemplate
    pim_catalog.entity.available_attributes.class:        Pim\Bundle\CatalogBundle\Model\AvailableAttributes
