Pim\Bundle\CatalogBundle\Model\Category:
    icon_class:  icon-category
    name:        Category
    description: Category allows to organize products

Pim\Bundle\CatalogBundle\Model\Product:
    icon_class:  icon-product
    name:        Product
    description: Product description
