parameters:
    pim_catalog.doctrine.query.product_query_builder.class: Pim\Bundle\CatalogBundle\Doctrine\Query\ProductQueryBuilder
    pim_catalog.doctrine.query.filter_registry.class: Pim\Bundle\CatalogBundle\Doctrine\Query\QueryFilterRegistry
    pim_catalog.doctrine.query.sorter_registry.class: Pim\Bundle\CatalogBundle\Doctrine\Query\QuerySorterRegistry
    pim_catalog.doctrine.query.field_filter_dumper.class:     Pim\Bundle\CatalogBundle\Doctrine\Query\FieldFilterDumper
    pim_catalog.doctrine.query.attribute_filter_dumper.class: Pim\Bundle\CatalogBundle\Doctrine\Query\AttributeFilterDumper

services:
    # deprecated : will be drop in 1.4
    pim_catalog.doctrine.product_query_builder:
        alias: pim_catalog.doctrine.query.product_query_builder

    pim_catalog.doctrine.query.product_query_builder:
        class: %pim_catalog.doctrine.query.product_query_builder.class%
        arguments:
            - '@pim_catalog.context.catalog'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.doctrine.query.filter_registry'
            - '@pim_catalog.doctrine.query.sorter_registry'

    pim_catalog.doctrine.query.filter_registry:
        class: %pim_catalog.doctrine.query.filter_registry.class%
        arguments:
            - '@pim_catalog.repository.attribute'

    pim_catalog.doctrine.query.sorter_registry:
        class: %pim_catalog.doctrine.query.sorter_registry.class%

    pim_catalog.doctrine.query.field_filter_dumper:
        class: %pim_catalog.doctrine.query.field_filter_dumper.class%
        arguments:
            - '@pim_catalog.doctrine.query.filter_registry'

    pim_catalog.doctrine.query.attribute_filter_dumper:
        class: %pim_catalog.doctrine.query.attribute_filter_dumper.class%
        arguments:
            - '@pim_catalog.doctrine.query.filter_registry'
            - '@pim_catalog.repository.attribute'
