pim_enrich_attributeoption_index:
    path: /{attribute_id}
    defaults: { _controller: pim_enrich.controller.attribute_option:indexAction }
    requirements:
        attribute_id: \d+
        _method:  GET
