parameters:
    oro_user.form.type.user.class:                   Pim\Bundle\UserBundle\Form\Type\UserType
    oro_user.form.handler.user.class:                Pim\Bundle\UserBundle\Form\Handler\UserHandler
    oro_user.form.handler.acl_role.class:            Pim\Bundle\UserBundle\Form\Handler\AclRoleHandler
    pim_user.form.type.acl_collection.class:         Pim\Bundle\UserBundle\Form\Type\PrivilegeCollectionType
    pim_user.context.user.class:                     Pim\Bundle\UserBundle\Context\UserContext
    pim_user.event_listener.user_preferences.class:  Pim\Bundle\UserBundle\EventListener\UserPreferencesListener
    pim_user.form.subscriber.user_preferences.class: Pim\Bundle\UserBundle\Form\Subscriber\UserPreferencesSubscriber
    pim_user.event_subscriber.group.class:           Pim\Bundle\UserBundle\EventSubscriber\GroupSubscriber

services:
    pim_user.form.type.acl_collection:
        class: %pim_user.form.type.acl_collection.class%
        tags:
            - { name: form.type, alias: oro_acl_collection }

    pim_user.context.user:
        class: %pim_user.context.user.class%
        arguments:
            - '@security.context'
            - '@pim_catalog.manager.locale'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.category'
            - %locale%
        calls:
            - [ setRequest, ['@?request='] ]

    oro_user.form.type.user:
        scope: request
        class: %oro_user.form.type.user.class%
        arguments:
            - '@security.context'
            - '@request'
            - '@pim_user.form.subscriber.user_preferences'
            - '@pim_user.repository.role'
            - '@pim_user.repository.group'
        tags:
            - { name: form.type, alias: oro_user_user }

    pim_user.form.subscriber.user_preferences:
        class: %pim_user.form.subscriber.user_preferences.class%
        arguments:
            - %pim_catalog.entity.category.class%

    pim_user.event_listener.user_preferences:
        class: %pim_user.event_listener.user_preferences.class%
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: doctrine.event_subscriber }

    pim_user.event_subscriber.group:
        class: %pim_user.event_subscriber.group.class%
        tags:
            - { name: kernel.event_subscriber }
