parameters:
    pim_enrich.normalizer.collection.class:             Pim\Bundle\EnrichBundle\Normalizer\CollectionNormalizer
    pim_enrich.normalizer.attribute_option.class:       Pim\Bundle\EnrichBundle\Normalizer\AttributeOptionNormalizer
    pim_enrich.normalizer.attribute_option_value.class: Pim\Bundle\EnrichBundle\Normalizer\AttributeOptionValueNormalizer

services:
   pim_enrich.normalizer.collection:
        class: %pim_enrich.normalizer.collection.class%
        tags:
            - { name: pim_serializer.normalizer }

   pim_enrich.normalizer.attribute_option:
        class: %pim_enrich.normalizer.attribute_option.class%
        tags:
            - { name: pim_serializer.normalizer }

   pim_enrich.normalizer.attribute_option_value:
        class: %pim_enrich.normalizer.attribute_option_value.class%
        tags:
            - { name: pim_serializer.normalizer }
