Pim\Bundle\CatalogBundle\Model\Currency:
    type: entity
    table: pim_catalog_currency
    repositoryClass: Pim\Bundle\CatalogBundle\Model\Repository\CurrencyRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 3
            unique: true
        activated:
            type: boolean
            column: is_activated
