Pim\Bundle\CatalogBundle\Model\ProductValueReferenceData:
    type: entity
    table: pim_catalog_product_value_reference_data
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    # should not be a one to one as you can have several same referentials (ie Color or Car)
    # for one product value => multi select
    oneToOne:
        productValue:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductValueInterface
            cascade:
                - remove
                - persist
                - refresh
                - detach
            inversedBy: referenceData
            joinColumns:
                value_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    # should not be hardcoded, should be injected via class metadata
#    manyToOne:
#        car:
#            targetEntity: Acme\Bundle\AppBundle\Entity\Car
#            inversedBy: data
#            joinColumn:
#                name: car_id
#                referencedColumnName: id
