Pim\Bundle\CatalogBundle\Model\ReferenceData:
    type: mappedSuperclass
    table: pim_catalog_reference_data
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        productValueReferenceData:
            targetEntity: Pim\Bundle\CatalogBundle\Model\ProductValueReferenceDataInterface
            cascade:
                - remove
                - persist
                - refresh
                - detach
            mappedBy: referenceData
